source: ./_src
destination: ./_dist
form_api: UDDJZxc4l42AZY5LETCT

title: Sydney Bouthsavong

instagram: "https://www.instagram.com/pastelskidney/"
email: "SydneyB@boneless.email.com"

exclude:
  - Gemfile